Address deprecation in Nutch codebase

diff --git a/.github/workflows/master-build.yml b/.github/workflows/master-build.yml
--- a/.github/workflows/master-build.yml
+++ b/.github/workflows/master-build.yml
@@ -13,7 +13,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-name: master pull request ci
+name: master branch ci
 on:
   push:
     branches: [master]
@@ -88,13 +88,33 @@ jobs:
               - 'ivy/ivy.xml'
       # run if the build configuration or both 'core' and 'plugins' files were changed
       - name: test all
+        id: build
         if: ${{ steps.filter.outputs.buildconf == 'true' || ( steps.filter.outputs.core  == 'true' && steps.filter.outputs.plugins  == 'true' ) }}
-        run: ant clean test -buildfile build.xml
+        run: ant clean test -buildfile build.xml | tee build.log
+        run: echo "BUILD_LOG=$(cat build.log)" >> $GITHUB_OUTPUT
       # run only if 'core' files were changed
       - name: test core
+        id: build
         if: ${{ steps.filter.outputs.core == 'true' && steps.filter.outputs.plugins == 'false' && steps.filter.outputs.buildconf == 'false' }}
-        run: ant clean test-core -buildfile build.xml
+        run: ant clean test-core -buildfile build.xml | tee build.log
+        run: echo "BUILD_LOG=$(cat build.log)" >> $GITHUB_OUTPUT
       # run only if 'plugins' files were changed
       - name: test plugins
+        id: build
         if: ${{ steps.filter.outputs.plugins == 'true' && steps.filter.outputs.core == 'false' && steps.filter.outputs.buildconf == 'false' }}
-        run: ant clean test-plugins -buildfile build.xml
+        run: ant clean test-plugins -buildfile build.xml | tee build.log
+        run: echo "BUILD_LOG=$(cat build.log)" >> $GITHUB_OUTPUT
+  check-deprecations:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Detect deprecation warnings
+        run: |
+          if grep -iEq "warning: \[deprecation\]" ${{ steps.build.outputs.BUILD_LOG }} ; then
+            echo "=========================================================="
+            echo "= Java deprecation warnings detected! Failing the build. ="
+            echo "==========================================================\n"
+            grep -iE "warning: \[deprecation\]" -A 2 ${{ steps.build.outputs.BUILG_LOG }}
+            exit 1
+          else
+            echo "No Java deprecation warnings found."
+          fi
